### ISSUE TITLE
On some machines GUI is not displayed properly in the terminal.

### ISSUE THREAD

**Issue by romansemko** [SemkoDev/nelson.cli#10]
![terminal](https://user-images.githubusercontent.com/2489829/34077395-88015402-e303-11e7-98c9-dd65dcda2da7.png)
The problem might be that the given terminal does not allow special chars. Why the first column is cut, however, I cannot explain.

**Comment by H3n-42** [comment]
Can confirm, seen on Ubuntu 16.04.3 LTS

**Comment by witwit** [comment]
I'm on it. Could reproduce this, thanks for reporting.

**Comment by witwit** [comment]
Could somebody please confirm if the problem still persists and report in such a case what kind of terminals fail? The terminal that I used to reproduce the issue looks acceptable on 0.2.2 now.

![whatsapp image 2017-12-18 at 15 34 05](https://user-images.githubusercontent.com/1893589/34111177-4a6facf4-e409-11e7-94dc-4092eaf4c2e1.jpeg)

**Comment by romansemko** [comment]
It's not in 0.2.2, yet. Please wait for 0.2.3

**Comment by romansemko** [comment]
fixed
