### ISSUE TITLE
Error starting nelson

### ISSUE THREAD

**Issue by tolotos-rgu** [SemkoDev/nelson.cli#22]
OS: Ubuntu  Xenial
Kernel: 4.4.27-x86_64-jb1

>npm install -g nelson.cli
>==> OK

>nelson --gui --getNeighbors
>==> see below

>/usr/local/lib/node_modules/nelson.cli/node_modules/external-ip/lib/extIP.js:5
>module.exports = (externalConfig = {}) => {
>                                                    ^
>SyntaxError: Unexpected token =
>    at exports.runInThisContext (vm.js:53:16)
>    at Module._compile (module.js:374:25)
>    at Object.Module._extensions..js (module.js:417:10)
>    at Module.load (module.js:344:32)
>    at Function.Module._load (module.js:301:12)
>    at Module.require (module.js:354:17)
>    at require (internal/module.js:12:17)
>    at Object.<anonymous> (/usr/local/lib/node_modules/nelson.cli/node_modules/external-ip/index.js:2:18)
>    at Module._compile (module.js:410:26)
>    at Object.Module._extensions..js (module.js:417:10)

**Comment by thisredone** [comment]
Is your node.js `at least version LTS 6.9.1`?

**Comment by romansemko** [comment]
Your node seems to be v 4.x. Please upgrade to at least 6.9.1
