### ISSUE TITLE
API not working properly

### ISSUE THREAD

**Issue by H3n-42** [SemkoDev/nelson.cli#29]
### Expected behaviour
get a response from the root endpoint "/"

### Actual behaviour
getting an empty or no response

### Steps to reproduce
when making the api call from the browser direct or via jquery i.e._
`$.getJSON("http://localhost:18600", function (data) {
        console.log(data);
    });`

only getting an emtpy response.

### Basic Info
* Operating System: Windows
* Node (npm) Version: 8.9.3 (5.5.1)
* IRI Version: 1.4.1.4
* Nelson version: 0.2.2

### Nelson Info
* Epoch: 3 
* Cycle: 35
* Connected peers: 5

**Comment by romansemko** [comment]
Cross-Origin issue. @witwit is preparing a PR for this.

**Comment by romansemko** [comment]
Fixed in 0.2.5
