### ISSUE TITLE
Running isMaster with outgoingMax set makes Nelson ignore the neighbour limits

### ISSUE THREAD

**Issue by romansemko** [SemkoDev/nelson.cli#31]
### Expected behaviour
Maximal neighbours connected should stay at 11 +/- 1.

### Actual behaviour
Over 3o neighbours are added!

### Steps to reproduce
Run nelson as entry node with isMaster and outgoingMax set.

### Basic Info
* Operating System: Linux
* Node (npm) Version: 6+
* IRI Version: 1.4.1.4
* Nelson version: 0.2.4

### Nelson Info
* Epoch: doesn't matter
* Cycle: doesn't matter
* Connected peers: 28

**Comment by suppqt** [comment]
can confirm.
29 Neighbours.

Nodejs:8.3.9
Iri: 1.4.1.4
Nelson 0.2.4
OS: Ubuntu 16.04

ismaster

**Comment by romansemko** [comment]
fixed with 0.2.5

**Comment by suppqt** [comment]
nvm
