### ISSUE TITLE
How do you use a static IP address with Nelson

### ISSUE THREAD

**Issue by Darren80** [SemkoDev/nelson.cli#33]
Is it in the config file? Also where is the config file located.

**Comment by H3n-42** [comment]
description of configuration is located here in the readme:
https://github.com/SemkoDev/nelson.cli#configuration

**Comment by romansemko** [comment]
Other Nelson instances see your (static) IP. No need to configure it. For everything else, check the README. If you need any help, please ask in the #nelson channel on slack. Thanks! :)
