### ISSUE TITLE
Limit the number of nodes

### ISSUE THREAD

**Issue by antonionardella** [SemkoDev/nelson.cli#38]
### Basic Info
* Operating System:
* Node (npm) Version:
* IRI Version:
* Nelson version:

### Nelson Info
* Epoch:
* Cycle:
* Connected peers:

**Comment by antonionardella** [comment]
Hello,

would it be possible to limit the number of nodes, neslon sends to IRI?

Come_from_beyond always confirms that the maximum number of IOTA nodes should be limited to 7.

If an IRI user already has some nodes configured and wanted to use nelson, this limit of 7 nodes is not configurable, or am I missing a setting somewhere?

Thanks

**Comment by ds2216** [comment]
you missed **--outgoingMax** and **--incominMax**

**Comment by romansemko** [comment]
Please use the parameters above, as @ds2216 pointed out. Thanks!
