### ISSUE TITLE
Closing Nelson 0.3.1 will also remove all static neighbors

### ISSUE THREAD

**Issue by chrisoro** [SemkoDev/nelson.cli#39]
### Expected behaviour
Closing Nelson should not remove static neighbors.
### Actual behaviour
Closing Nelson does remove static neighbors.
### Steps to reproduce
- Start IRI with at least one static neighbor
- Check neighbor count via api -> should say 1 (or X).
- Start Nelson with --getNeighbors
- Check neighbor count again should say 1+Y (or X+Y)
- Close Nelson
- Check neighbor count again and it says 0

### Basic Info
* Operating System:
* Node (npm) Version: 8.9.3
* IRI Version: 1.4.1.4
* Nelson version: 0.3.1

**Comment by romansemko** [comment]
Should be fixed with 0.3.5
