### ISSUE TITLE
test peer-test.js fails

### ISSUE THREAD

**Issue by ccmawo** [SemkoDev/nelson.cli#43]
### Expected behaviour
The test should not fail.

### Actual behaviour
 FAIL  src/node/__tests__/peer-test.js
  ● Peer › should return correct tcp, http and hostname strings

    expect(received).toEqual(expected)
    
    Expected value to equal:
      "tangle.com/666/777/888"
    Received:
      "tangle.com/666/777/888/0/udp"
      
      at Object.<anonymous> (src/node/__tests__/peer-test.js:21:36)
      at process._tickCallback (internal/process/next_tick.js:109:7)

### Steps to reproduce
git clone https://github.com/SemkoDev/nelson.cli.git
git checkout 0.3.12-beta
yarn install --pure-lockfile
yarn make 

### Basic Info
* Operating System: Ubuntu 16.04 LTS
* Node (npm) Version: node v6.12.2, npm 3.10.10
* IRI Version: 1.4.1.4
* Nelson version: 0.3.12-beta

**Comment by H3n-42** [comment]
fixed by pr#40
