### ISSUE TITLE
Unexpected death of Nelson process - TCP error

### ISSUE THREAD

**Issue by stevebourg** [SemkoDev/nelson.cli#45]
### Expected behaviour
Uninterrupted operation.

### Actual behaviour
Nelson died with:
Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at TCP.onread (net.js:568:26)

### Steps to reproduce
Unknown.  Nelson had been running for 10 hours and 15 minutes (scrollback in screen session).  

### Basic Info
* Operating System: Ubuntu 17.10
* Node (npm) Version: 3.5.2
* IRI Version: 1.4.1.6
* Nelson version: 0.3.12

### Nelson Info
* Epoch: 112 (at 1% of current epoch)
* Cycle: 559 (at 1% of currency cycle)
* Connected peers: 9

**Comment by stevebourg** [comment]
Incident occurred again.
Online: 6 hours 14 minutes
Epoch: 69
Cycle: 341
epoch 35%
cycle 58%
Connected 8

Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at TCP.onread (net.js:568:26)

**Comment by stevebourg** [comment]
Issued occurred once again with Nelson version 0.3.15

Online: 6 hours 30 minutes
Epoch: 71
Cycle: 353
epoch 81%
cycle 62%
Connected: 10

Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at TCP.onread (net.js:568:26)

Just to note - this failure leaves Nelson's active neighbors in the IRI, which soon become stale.

**Comment by romansemko** [comment]
Closing this, hoping that this issue is solved in the next release.

**Comment by devhen** [comment]
Just got this error with nelson 0.3.16. It had been running for about 15 minutes.

CentOS 7
nodejs 6.12.2-1.el7
npm 3.10.10-1.6.12.2.1.el7
iri 1.4.1.6
nelson 0.3.16

**Comment by stevebourg** [comment]
Experienced against with Nelson 0.3.16 after 2 hours 22 minutes.

**Comment by stevebourg** [comment]
Occurs when using --IRIProtocol udp 
Nelson 0.3.16
