### ISSUE TITLE
Node NOT SYNCED error

### ISSUE THREAD

**Issue by lapwat** [SemkoDev/nelson.cli#49]
### Expected behaviour
Hello, I have run my own IOTA full node (iri + nelson) on a VPS.

### Actual behaviour
When I try to connect to my server via a desktop client, I get NOT SYNCED error when clicking on LOGIN button. Other official nodes work well.

### Steps to reproduce
On the server:
`docker run -d --net host -p 14265:14265 --name iri iotaledger/iri`
`docker run -d --net host -p 18600:18600 --name nelson romansemko/nelson.cli -r localhost -i 14265 -u 14777 -t 15777 --neighbors "mainnet.deviota.com/16600 mainnet2.deviota.com/16600 mainnet3.deviota.com/16600 iotairi.tt-tec.net/16600"`

On your computer:
- Launch IOTA Desktop Wallet
- Tools -->  Edit node configuration
- Set custom host to http://iota.full.node.com:14265
- Save
- Enter a seed and click LOGIN

My quesions are,
Do I have to wait for my full node to be fully synced ? Is the sync process broken ?

Thanks for reading me,
lapwat

### Basic Info
* Operating System: Ubuntu Zesty (17.04 latest)
* Node (npm) Version: Docker image romansemko/nelson.cli:latest
* IRI Version: 1.4.1.6 Docker image iotaledger/iri:latest
* Nelson version:  0.3.16 Docker image romansemko/nelson.cli:latest

### Nelson Info
* Epoch: 1200
* Cycle: 60
* Connected peers: 3

**Comment by H3n-42** [comment]
you should wait for your node to be synced fully, before using the light wallet on it.

**Comment by lapwat** [comment]
I tried to connect this morning and it perfectely worked. I just had to wait for my full node to find enough stable neighbors to sync fully :)
Thank you so much.
lapwat
