### ISSUE TITLE
Still something wrong with adding/removing neighbors

### ISSUE THREAD

**Issue by chrisoro** [SemkoDev/nelson.cli#50]
Hey @romansemko, last time I found out that static neighbors were removed in like 0.3.1 or so.. Since then I have been monitoring the neighbor count closely. I observed the same two problems on my 3 nodes:

### Expected behaviour
1. Amount of added neighbors should not violate the settings
2. When closing nelson it should remove all previously added neigbhbors

### Actual behaviour
1. Having 2 static neighbors and setting nelson to 4 / 3 (in/out) there are sometimes up to 13 neighbors reported by iri
2.  I often end up with 3 sometimes up to 5 neighbors after closing nelson. Substracting my 2 static neighbors, that leaves me with 1 to 3 added neighbors (by nelson) that it didn't remove properly on exit

### Steps to reproduce
- Start iri and nelson
- Wait until sync
- Look at neighbor count in iri (see that it's not following nelsons config)
- Close nelson
- Look at neighbor count in iri (see that you have more neighbors than before starting nelson)

### Basic Info
* Operating System: Ubuntu 17.10 (x64)
* Node (npm) Version: node: 8.9.4 (npm: 5.6)
* IRI Version: 1.4.1.6
* Nelson version: 0.3.16

**Comment by chrisoro** [comment]
Woke up today with one node having 20(!!!) active neighbors. After stopping nelson it still had 10. I think it sometimes 'forgets' about the added neighbors (or the remove failed but nelson thinks it succeeded) and keeps on going.

**Comment by H3n-42** [comment]
somehow i can't reproduce this. Do you mean aktive neighbors or total neighbors? 
where do you get the neighbor count from?

**Comment by chrisoro** [comment]
Calling iri api with getNeighbors

**Comment by chrisoro** [comment]
Calling iri api with getNeighbors

**Comment by romansemko** [comment]
Please try version 0.3.21. **Restart IRI before starting the new Nelson version**

Please re-open the ticket or create a new one if you see this problem persist.

**Comment by chrisoro** [comment]
Observed again right now on 3 different nodes. Stopped nelson because I wanted to update to 0.4 and it didn't remove all neighnors (3, 1, 1 left)

**Comment by romansemko** [comment]
Please stop IRI and nelson, install 0.4.0 and restart IRI/Nelson. 0.4.0 fixed another neighbours leak to IRI. This might have been in your case..
