### ISSUE TITLE
Can not start nelson

### ISSUE THREAD

**Issue by mstrewe** [SemkoDev/nelson.cli#52]
### Expected behaviour
nelson should run
### Actual behaviour
nelson craches with following output:

    Unhandled Rejection at: Promise Promise {
      <rejected> TypeError: URL is not a constructor
      at /usr/local/lib/node_modules/nelson.cli/dist/node/iri.js:79:40
      at Array.map (native)
      at /usr/local/lib/node_modules/nelson.cli/dist/node/iri.js:78:55
      at makeRequest.prepareResult 
      (/usr/local/lib/node_modules/nelson.cli/node_modules/iota.lib.js/lib/utils/makeRequest.js:313:12)
      at request.onreadystatechange 
      (/usr/local/lib/node_modules/nelson.cli/node_modules/iota.lib.js/lib/utils/makeRequest.js:71:25)
      at dispatchEvent 
     (/usr/local/lib/node_modules/nelson.cli/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/usr/local/lib/node_modules/nelson.cli/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/nelson.cli/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7) } reason: TypeError: URL is not a constructor
    at /usr/local/lib/node_modules/nelson.cli/dist/node/iri.js:79:40
    at Array.map (native)
    at /usr/local/lib/node_modules/nelson.cli/dist/node/iri.js:78:55
    at makeRequest.prepareResult (/usr/local/lib/node_modules/nelson.cli/node_modules/iota.lib.js/lib/utils/makeRequest.js:313:12)
    at request.onreadystatechange (/usr/local/lib/node_modules/nelson.cli/node_modules/iota.lib.js/lib/utils/makeRequest.js:71:25)
    at dispatchEvent (/usr/local/lib/node_modules/nelson.cli/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/usr/local/lib/node_modules/nelson.cli/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/nelson.cli/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)

### Steps to reproduce
start nelson with following command

    nelson --gui --isMaster --epochInterval 180 --neighbors "mainnet.deviota.com/16600 mainnet2.deviota.com/16600 iotairi.tt-tec.net/16600 voss-hosting.de/16600 iotanode.party/16600 nelson.vanityfive.de/16600 45.77.187.45/16600 tanglenode.de/16600 nelson.iota.fm/16000"

### Basic Info
* Operating System:
 Ubuntu-1710-artful-64-minimal
* Node (npm) Version:
3.5.2
* IRI Version:
1.4.1.7
* Nelson version:
0.3.21

**Comment by rosstimson** [comment]
I am also seeing this error after restarting IRI and Nelson recently.  I have been using this setup for some time now without issue.

In the past I've managed to fix some oddness when starting Nelson by removing the `neighbors.db` file and letting it recreate it.  This doesn't work on this occasion though.

## Basic Info

OS:  Amazon Linux 2
NodeJS:  v6.12.2
Nelson: 0.3.21
IRI:  1.4.1.7

## Nelson Config

```
[nelson]
cycleInterval = 60
epochInterval = 300
apiPort = 18600
apiHostname = 127.0.0.1
port = 16600
IRIHostname = localhost
IRIPort = 14265
TCPPort = 15777
UDPPort = 14777
dataPath = /opt/nelson/neighbors.db
isMaster = false
silent = false
gui = false
getNeighbors = https://raw.githubusercontent.com/SemkoDev/nelson.cli/master/ENTRYNODES
```

## Log Extract

```
Jan 28 20:27:53 ip-10-0-0-254 nelson[1916]: 8:27:53 PM.736        16600::IRI   Neighbors removed (if there were any): udp://iota.bluemx.de:14600
Jan 28 20:27:53 ip-10-0-0-254 nelson[1916]: 8:27:53 PM.738        16600::NODE  connection closed iota.bluemx.de:16600 (remotely dropped)
Jan 28 20:28:03 ip-10-0-0-254 nelson[1916]: 8:28:03 PM.398        16600::NODE  connecting peer node.io7a.com:16600
Jan 28 20:28:03 ip-10-0-0-254 nelson[1916]: 8:28:03 PM.399        16600::NODE  connecting peer 136.243.57.228:16600
Jan 28 20:28:03 ip-10-0-0-254 nelson[1916]: 8:28:03 PM.400        16600::NODE  connecting peer eu1.tangleno.de:16600
Jan 28 20:28:03 ip-10-0-0-254 nelson[1916]: 8:28:03 PM.436        16600::IRI   Neighbors removed (if there were any): udp://136.243.57.228:14600
Jan 28 20:28:03 ip-10-0-0-254 nelson[1916]: 8:28:03 PM.437        16600::NODE  connection closed 136.243.57.228:16600 (remotely dropped)
Jan 28 20:28:03 ip-10-0-0-254 nelson[1916]: 8:28:03 PM.765        16600::IRI   Neighbors removed (if there were any): udp://node.io7a.com:14600
Jan 28 20:28:03 ip-10-0-0-254 nelson[1916]: 8:28:03 PM.765        16600::NODE  connection closed node.io7a.com:16600 (remotely dropped)
Jan 28 20:28:07 ip-10-0-0-254 nelson[1916]: 8:28:07 PM.910        16600::NODE  terminating...
Jan 28 20:28:07 ip-10-0-0-254 nelson[1916]: 8:28:07 PM.916        16600::IRI   Neighbors removed (if there were any): udp://mainnet.deviota.com:14600, udp://iotanode.party:14600, udp://eu1.tangleno.de:14600
Jan 28 20:28:08 ip-10-0-0-254 nelson[1916]: Unhandled Rejection at: Promise Promise {
Jan 28 20:28:08 ip-10-0-0-254 nelson[1916]: <rejected> TypeError: URL is not a constructor
Jan 28 20:28:08 ip-10-0-0-254 nelson[1916]: at /usr/lib/node_modules/nelson.cli/dist/node/iri.js:384:38
Jan 28 20:28:08 ip-10-0-0-254 nelson[1916]: at Array.map (native)
Jan 28 20:28:08 ip-10-0-0-254 nelson[1916]: at /usr/lib/node_modules/nelson.cli/dist/node/iri.js:382:51
Jan 28 20:28:08 ip-10-0-0-254 nelson[1916]: at makeRequest.prepareResult (/usr/lib/node_modules/nelson.cli/node_modules/iota.lib.js/lib/utils/makeRequest.js:313:12)
Jan 28 20:28:08 ip-10-0-0-254 nelson[1916]: at request.onreadystatechange (/usr/lib/node_modules/nelson.cli/node_modules/iota.lib.js/lib/utils/makeRequest.js:71:25)
Jan 28 20:28:08 ip-10-0-0-254 nelson[1916]: at dispatchEvent (/usr/lib/node_modules/nelson.cli/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
Jan 28 20:28:08 ip-10-0-0-254 nelson[1916]: at setState (/usr/lib/node_modules/nelson.cli/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
Jan 28 20:28:08 ip-10-0-0-254 nelson[1916]: at IncomingMessage.<anonymous> (/usr/lib/node_modules/nelson.cli/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
Jan 28 20:28:08 ip-10-0-0-254 nelson[1916]: at emitNone (events.js:91:20)
Jan 28 20:28:08 ip-10-0-0-254 nelson[1916]: at IncomingMessage.emit (events.js:185:7) } reason: TypeError: URL is not a constructor
Jan 28 20:28:08 ip-10-0-0-254 nelson[1916]: at /usr/lib/node_modules/nelson.cli/dist/node/iri.js:384:38
Jan 28 20:28:08 ip-10-0-0-254 nelson[1916]: at Array.map (native)
Jan 28 20:28:08 ip-10-0-0-254 nelson[1916]: at /usr/lib/node_modules/nelson.cli/dist/node/iri.js:382:51
Jan 28 20:28:08 ip-10-0-0-254 nelson[1916]: at makeRequest.prepareResult (/usr/lib/node_modules/nelson.cli/node_modules/iota.lib.js/lib/utils/makeRequest.js:313:12)
Jan 28 20:28:08 ip-10-0-0-254 nelson[1916]: at request.onreadystatechange (/usr/lib/node_modules/nelson.cli/node_modules/iota.lib.js/lib/utils/makeRequest.js:71:25)
Jan 28 20:28:08 ip-10-0-0-254 nelson[1916]: at dispatchEvent (/usr/lib/node_modules/nelson.cli/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
Jan 28 20:28:08 ip-10-0-0-254 nelson[1916]: at setState (/usr/lib/node_modules/nelson.cli/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
Jan 28 20:28:08 ip-10-0-0-254 nelson[1916]: at IncomingMessage.<anonymous> (/usr/lib/node_modules/nelson.cli/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
Jan 28 20:28:08 ip-10-0-0-254 nelson[1916]: at emitNone (events.js:91:20)
Jan 28 20:28:08 ip-10-0-0-254 nelson[1916]: at IncomingMessage.emit (events.js:185:7)
```

**Comment by rosstimson** [comment]
Also tried upgrading to IRI 1.4.2.1 (post snapshot) and cleared out the IRI database as instructed.  This bug persists after that too.

**Comment by rosstimson** [comment]
Still the same after upgrading to nelson 0.3.22 as well.

**Comment by ds2216** [comment]
Node(JS) version should be 8.9.4 or higher

**Comment by rosstimson** [comment]
@ds2216  Thank you.  I hadn't realised the pre-requisites had changed and Amazon Linux has an older version in the package repo.

@mstrewe Uninstalling NodeJS package and then manually installing the latest LTS (v8.9.4) direct from  nodejs.org seems to have fixed this for me.

**Comment by mstrewe** [comment]
Thank you for your help!! Installing nodejs manually worked for me too.

**Comment by HerrMuellerluedenscheid** [comment]
Hey, I ran into the same issue. Nelson should check the nodejs version an throw a warning message if nodejs -version < 8.9.4.  Would be a nice feature and lead to much quicker solutions for many people, I guess.

edit: Ok, it's written in the documentation. But some people tend to skip documentations. Shame on them :blush:

**Comment by medisoft** [comment]
I have the same problem

```
node --version
v8.9.4

14:58:53.393	16600::IRI   Static neighbors: ahiota5.ddns.net,iotavps.websioux.com,iota.preissler.me,iota.cdapplications.be
14:58:54.769	16600::NODE  terminating...
Unhandled Rejection at: Promise Promise {
  <rejected> Error: "toString()" failed
    at stringSlice (buffer.js:560:43)
    at Buffer.toString (buffer.js:633:10)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:506:23) } reason: Error: "toString()" failed
    at stringSlice (buffer.js:560:43)
    at Buffer.toString (buffer.js:633:10)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:506:23)
```

But it seems that the problem was a corrupt neighbors.db, removed it and it worked again
