### ISSUE TITLE
Increasing CPU usage over time

### ISSUE THREAD

**Issue by huggre** [SemkoDev/nelson.cli#54]
### Actual behaviour
5 minutes after starting iri/nelson my CPU usage is typically about 40%
As hours goes by i see a gradual increase of CPU usage to the point where it reaches 90-100%. 
This would typically occur after 24 hours.
At this point i also notice that the number of active connections are very low (0 or 1 connections)
Now, if i close and restart nelson (without closing iri) things goes back to normal (40% CPU and normal connection count)

Note! Im also running the Carriota Field service on this server.

### Basic Info
* Operating System:
Unbuntu
* Node (npm) Version:
5.6.0
* IRI Version:
1.4.2.1
* Nelson version:
0.4.0

### Nelson Info
* Epoch:
* Cycle:
* Connected peers:

**Comment by Nick2bad4u** [comment]
I usually run into a similar issue although not as fast as 5 minutes after. After running nelson for about 2 days of uptime, it seems to spam add/remove peers very quickly causing CPU usage to spike, also memory spikes. 

I think Nelson should limit how fast it can add/remove peers

**Comment by Fabryprog** [comment]
+1 

I have similar problem into my full node!

I am using default configuration
